name: Docs
on:
  push:
    branches:
      - trunk
    tags:
      - "v*"
  workflow_dispatch:
    inputs:
      version:
        description: "Version to deploy (e.g. 0.1.1, 0.1.1-beta01)"
        required: true
        default: ""
permissions:
  contents: write
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
        with:
          fetch-depth: 0
      - uses: actions/setup-python@v7
        with:
          python-version: 3.x
      - run: pip install zensical
      - run: pip install git+https://github.com/squidfunk/mike.git
      - name: Configure Git
        run: |
          git config user.name github-actions[bot]
          git config user.email github-actions[bot]@users.noreply.github.com
      - name: Copy docs
        run: cp CHANGELOG.md docs/changelog.md
      - name: Deploy docs
        run: |
          if [[ -n "${{ inputs.version }}" ]]; then
          version="${{ inputs.version }}"
          mike deploy --push "$version"
        
          elif [[ "$GITHUB_REF_NAME" == v* ]]; then
          version="${GITHUB_REF_NAME#v}"
          mike deploy --push "$version" --update-aliases stable latest
        
          else
          mike deploy --push dev
          fi
